# Generated by Django 5.2.11 on 2026-02-11 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('template_text', models.TextField(help_text='Template with placeholders like {chief_complaint}, {signs_symptoms}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_identifier', models.CharField(help_text='Patient identifier or case number', max_length=100)),
                ('chief_complaint', models.CharField(help_text='Main complaint or reason for consultation', max_length=500)),
                ('signs_symptoms', models.TextField(help_text='Detailed signs and symptoms reported by patient')),
                ('history_present_illness', models.TextField(blank=True, help_text='History of present illness (HPI)')),
                ('relevant_medical_history', models.TextField(blank=True, help_text='Relevant past medical history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('triage', 'Mock Triage'), ('guidelines', 'Mock Guidelines'), ('combined', 'Combined Pro-Prompt')], default='combined', max_length=20)),
                ('generated_prompt', models.TextField(help_text='The AI-ready prompt combining subjective data and professional context')),
                ('triage_context', models.TextField(blank=True, help_text='Additional context for triage decision-making')),
                ('guidelines_context', models.TextField(blank=True, help_text='Clinical guidelines and protocols to consider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompts', to='scc_prompts.patientcomplaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
